### ISSUE TITLE
ImportError: No module named klampt

### ISSUE THREAD

**Issue by yunxiaoshan** [krishauser/pyOptimalMotionPlanning#2]
Should I install it first?Ｉtry to install the deb. and I also download a Python binding, lots of dependences are required... Is there a simple way to add that?

**Comment by lohipoo** [comment]
把klampt改成..klampt就好了

**Comment by handlerww** [comment]
just modify error files,
import klampt   -->  import  ..klampt

**Comment by krishauser** [comment]
Hi lohipoo, thanks for catching that issue, do you mind submitting a pull request for it?
